### ISSUE TITLE
Inconsistent file argument 

### ISSUE THREAD

**Issue by ltfschoen** [nikhilkumarsingh/content-downloader#8]
In ctdl.py it uses `-g` for the file_type flag, but in the Readme that uses `ctdl` library it uses `-f` for file_type flag

**Comment by nikhilkumarsingh** [comment]
-g has been implemented by you in your pull request @ltfschoen

**Comment by nikhilkumarsingh** [comment]
Why do you want to use -g instead of -f btw?
